name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod || npx ng build --configuration production

      # SPA: fallback para rotas
      - name: Add 404.html for SPA routes
        run: cp dist/gaulia-tech/browser/index.html dist/gaulia-tech/browser/404.html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/gaulia-tech/browser
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
